In [1]:
import torch
torch.__version__

'2.3.1+cu118'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.dtype

(tensor([[0.4261, 0.6274, 0.3767, 0.5701],
         [0.4016, 0.6746, 0.2035, 0.4965],
         [0.0504, 0.2460, 0.2152, 0.8472]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
zeros = torch.zeros(3, 4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(3, 4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None, 
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [22]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [23]:
tensor * 10

tensor([10, 20, 30])

In [24]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [25]:
tensor += 10
tensor

tensor([1, 2, 3])

In [26]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [27]:
tensor

tensor([1, 2, 3])

In [28]:
tensor * tensor

tensor([1, 4, 9])

In [29]:
tensor.matmul(tensor)

tensor(14)

In [30]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]],
                        dtype=torch.float32)
tensor_B = torch.tensor([[7, 10], 
                         [8, 11],
                         [9, 12]],
                        dtype=torch.float32)
# torch.matmul(tensor_A, tensor_B) # matrix shape will not match

output = torch.matmul(tensor_A, tensor_B.T)
output2 = torch.mm(tensor_A.T, tensor_B)
output, output2

(tensor([[ 27.,  30.,  33.],
         [ 61.,  68.,  75.],
         [ 95., 106., 117.]]),
 tensor([[ 76., 103.],
         [100., 136.]]))

In [31]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)
x.shape, output.shape, output

(torch.Size([3, 2]),
 torch.Size([3, 6]),
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
        grad_fn=<AddmmBackward0>))

In [32]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
x.min()

tensor(0)

In [34]:
x.max()

tensor(90)

In [35]:
x.type(torch.float32).mean()

tensor(45.)

In [36]:
x.sum()

tensor(450)

In [37]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [38]:
tensor = torch.arange(10, 100, 10)
tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
tensor.argmax(), tensor.argmin()

(tensor(8), tensor(0))

In [40]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [41]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [43]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [44]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [45]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [46]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [47]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [53]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [54]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7.])

In [56]:
x_unsqeezed = x_squeezed.unsqueeze(dim=0)
x_unsqeezed

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [57]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [59]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [61]:
x[:, 0], x[:, :, 1], x[:, 1, 1]

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]), tensor([5]))

In [62]:
x[0, 0, :]

tensor([1, 2, 3])

In [63]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [64]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [65]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [68]:
import random
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Excerices

In [70]:
x = torch.rand(7, 7)
x

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [71]:
y = torch.rand(1, 7)
torch.matmul(x, y.T)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [73]:
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
x = torch.rand(7, 7)

torch.random.manual_seed(seed=RANDOM_SEED)
y = torch.rand(1, 7)

x, y, torch.mm(x, y.T)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]))

In [74]:
x.max(), x.min()

(tensor(0.9527), tensor(0.0223))

In [75]:
x.argmax(), x.argmin()

(tensor(26), tensor(12))